### PR TITLE
Fix prom-client DeprecationWarning

### PR DESCRIPTION
**Pull request by spathon**
Fixes `DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated` [prom-client 10.0.0](https://github.com/siimon/prom-client/blob/master/CHANGELOG.md#breaking-1)

Edit: Removed the express check as commented in #34 and fixed in #37

### CODE REVIEW

**Comment by spathon** [comment]
@roylines What's required to get this merged?

**Comment by Elexy** [comment]
+1

**Comment by yciabaud** [comment]
Please merge this, we are tired of having warnings !
Thanks for the software BTW

**Comment by yciabaud** [comment]
Awesome thanks!

**Pull request merged**
