### PR TITLE
remove res.charSet fixes #34

### LINKED ISSUE #34: TypeError: res.charSet is not a function
Using express 4 the `res.charSet` has been deprecated and not supported anymore, the error is caused by [https://github.com/roylines/node-epimetheus/blob/master/lib/restify.js#L20](https://github.com/roylines/node-epimetheus/blob/master/lib/restify.js#L20) 

More info on the deprecated function [https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x#connects-patches](https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x#connects-patches)

at the moment is express 4 is in use it's a breaking change, it's easily fixable, I'll submit a PR as soon as I can

### PR DESCRIPTION
**Pull request by matteo-hertel**
super simple fix to support express4 breaking change of removing `res.charSet` fixes #34

### CODE REVIEW

**Comment by vernak2539** [comment]
@roylines mind taking a look at this? running into this issue as well

**Comment by roylines** [comment]
There are failing tests. Please fix and ensure they are checking for both content-type and charset. Need to be sure this works for restify too. Once done, I'd be happy to merge.

**Comment by vernak2539** [comment]
Are the tests running on a CI somewhere?

**Comment by vernak2539** [comment]
So it seems the real problem is that with express v4, it thinks it's restify...

**Comment by matteo-hertel** [comment]
I'll have a look as soon as I can, sorry about that

**Comment by roylines** [comment]
You can log into circleci - and it will be building your branches.

**Comment by spathon** [comment]
I had the same issue because it fails the express checks which was the main reason I started my PR #33

**Comment by vernak2539** [comment]
@spathon maybe it would be good to decouple #33 as it's aim is to solve two problems, not just the express issue?

**Comment by matteo-hertel** [comment]
After some digging I found out 1) why my tests were always passing, I had another service running on port 3000, maybe the test port should be configurable somewhere and 2) what was the problem with my changes, turned out that restify has a `end` method to send the response, but instead `send` was used causing the native Node handler to send the response and setting the content type to text/plain

SO was key to solving this

[https://stackoverflow.com/questions/28680755/setting-content-type-header-with-restify-results-in-application-octet-stream](https://stackoverflow.com/questions/28680755/setting-content-type-header-with-restify-results-in-application-octet-stream)

now tests are green and I've merged with the base branch, should be good to go

thanks!

**Comment by spathon** [comment]
@vernak2539 True will do that during the week

**Comment by vernak2539** [comment]
@spathon I've fixed it here https://github.com/roylines/node-epimetheus/pull/37. Hopefully this fixes our issue!

**Pull request merged**
