### PR TITLE
All tests passing

### PR DESCRIPTION
**Pull request by diasdavid**
Hi @roylines! Thank you for creating this module, it was the fastest way to get prometheus up and running for a simple service I've just created.

In order for it to work, I had to fix some things internally as APIs from restify, express and hapijs changed (I'm just using hapijs, but I figured I would fix all of them). With this PR:

- [x] All tests are passing again
- [x] Migration to StandardJS CodeStyle (it helps to keep styling coherent)
- [x] Use of semver for deps.
- [x] Remove of PeerDep and make prom-client an actual dep.

Let me know if you agree with all the changes. Thanks!

### CODE REVIEW

**Comment by roylines** [comment]
Thank-you David for this. I will take a look over the next couple of days.

**Comment by roylines** [comment]
published as epimetheus@1.0.50

**Comment by diasdavid** [comment]
Woa, that was super fast. Thanks @roylines ! 🌟

**Comment by roylines** [comment]
David, 
Does this close any of the outstanding issues on this project?
Roy.

**Comment by diasdavid** [comment]
It fixes:
- https://github.com/roylines/node-epimetheus/issues/30
- https://github.com/roylines/node-epimetheus/issues/25
- https://github.com/roylines/node-epimetheus/issues/20

**Pull request merged**
